# -*- coding: utf-8 -*-
"""Decorators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HEGOoBr0qsw8LwYfG7x1-A_7IvA-yUIC
"""

def my_decorator(func):
    def wrapper():
        print("Before the function is called.")
        func()
        print("After the function is called.")
    return wrapper

@my_decorator
def say_hello():
    print("Hello World!")

# Call the decorated function
say_hello()

# Output:
# Before the function is called.
# Hello World!
# After the function is called.

